### ISSUE TITLE
[BUG] Errors

### ISSUE THREAD

**Issue by ehl0el** [DVDishka/Backuper#10]
**Specify your operating system, minecraft server core and minecraft version**
1.20.4 
**Enter your config**

![](https://puu.sh/K1XMu/36a87e4426.png)

**Describe the bug**

errors when server starts. doesnt backup

**Comment by DVDishka** [comment]
Show me your config.yml please

**Comment by ehl0el** [comment]
> Show me your config.yml please

wait i didnt even check that. for some reason the only thing in my config was 

```
lastBackup: _________
lastChange: __________
```

but i never removed or changed the config since last time.

**Comment by ehl0el** [comment]
Now I'm having another issue, my server is not starting when I changed "afterBackup:" to restart. The server shut down when it backed up and didn't start again. Now when I try to start my server im getting this error. How do I fix it?


![](https://puu.sh/K1YjC/1ed3fbc9c0.png)

**Comment by ehl0el** [comment]
i rebooted my VM and its good now. i wont use the  restart option anymore.

**Comment by DVDishka** [comment]
![image](https://github.com/DVDishka/Backuper/assets/108480301/7f63bd75-321b-41a1-bf03-f967dfeee41e)
As i said here it is better to use STOP with auto-start server script

**Comment by DVDishka** [comment]
So how did you solve the first problem?

**Comment by ehl0el** [comment]
> So how did you solve the first problem?



> > Show me your config.yml please
> 
> wait i didnt even check that. for some reason the only thing in my config was
> 
> ```
> lastBackup: _________
> lastChange: __________
> ```
> 
> but i never removed or changed the config since last time.

the config cleared for some reason and only the first two lines were there. i just reset the config file too what it was before. i never touched the config or deleted anything though.

**Comment by DVDishka** [comment]
Ok, did restart solve yoursecond problem?

**Comment by ehl0el** [comment]
yes, rebooting my VM fixed it.

**Comment by DVDishka** [comment]
Thanks for tou report
