### ISSUE TITLE
Add ETA to unzip and zip operations [IDEA]

### ISSUE THREAD

**Issue by masuteri** [DVDishka/Backuper#11]
I think adding an eta to how long the backup file is going to take to unzip would be very useful especially if it's a large file. You'd want to know for how long your server is running on low tps, right?

I am sorry if you don't take suggestions

**Comment by DVDishka** [comment]
Thank you for your idea, i do take any feedback. I will try to find the way how to calculate ETA. Also you said about low tps. Do you really have this problem? The backup process runs in an asynchronous thread, and it should not affect server performance. If you have low tps during backup, please let me know how many cores your system has

**Comment by DVDishka** [comment]
I will make a percentage status of the task so you can roughly understand how long it will take to complete the task. Thanks for the idea
