### ISSUE TITLE
[IDEA] Add support for SFTP/FTP

### ISSUE THREAD

**Issue by dsbilling** [DVDishka/Backuper#12]
I would love to have support for sending the backup files to another location than the server itself, like an SFTP/FTP server.

**Comment by DVDishka** [comment]
Yes, thought about that, but have been implementing more general functions so far. Thanks for the suggestion, I will add it in the future (maybe not in the next version, but most likely in the next one after that). Glad to hear that somebody needs it

**Comment by DVDishka** [comment]
SFTP support will be added in the 2.1.0 release

**Comment by DVDishka** [comment]
FTP and SFTP support added in 3.0.0 version
