### ISSUE TITLE
[BUG] Folia 1.20.4 get error

### ISSUE THREAD

**Issue by xiaoyueyoqwq** [DVDishka/Backuper#14]
OS：WindowsServer2016
logs: https://paste.ubuntu.com/p/Yy8g8KgHzn/
when plugin reload or loaded it will printed this err log, *yap...only this*

**Comment by DVDishka** [comment]
Can you send me your config?

**Comment by xiaoyueyoqwq** [comment]
> Owner

here: https://paste.ubuntu.com/p/qFBq87FnHh/

**Comment by DVDishka** [comment]
Your backup period is set to -1. That means you want to make backups every -1 minute)

**Comment by xiaoyueyoqwq** [comment]
> I don't think you understand how the configuration works. If you describe to me exactly what you want, I will help you.

i want to set auto-backup at 3am. everyday, so i write this config like this

**Comment by DVDishka** [comment]
I found an issue, please, set your backupPeriod to 1440, I will fix it today

**Comment by DVDishka** [comment]
Thanks for your report

**Comment by xiaoyueyoqwq** [comment]
> Thanks for your report

your welcome :>, and i want gave you some advice for this plugin, like add **compression-level** and **print backup ETA** or **add a hook link to OneDrive/Google Drive and upload files** feature in plugin, that must make this plugin cool!
