### ISSUE TITLE
[BUG] v2.0.2-folia Cannot work on 1.20.4

### ISSUE THREAD

**Issue by xiaoyueyoqwq** [DVDishka/Backuper#22]
![image](https://github.com/DVDishka/Backuper/assets/71379165/18510b79-3157-4d53-bdd7-1104933e3f87)
Here is logs, is that truly cannot support 1.20.4? If that's ture, I suppose to downgrade plugin

**Comment by DVDishka** [comment]
If it is old Folia build you have to use Backuper-2.0.2, not Folia edition

**Comment by DVDishka** [comment]
Does it work now?

**Comment by DVDishka** [comment]
Thanks for your report
