### ISSUE TITLE
[BUG] Auto check for updates caused the server startup process to stuck for a long time.

### ISSUE THREAD

**Issue by LrbsX** [DVDishka/Backuper#24]
**Specify your operating system, minecraft server core and minecraft version**
Windows Server 2022
"leaves"server 1.20.1(a fork of paper,  https://github.com/LeavesMC/Leaves)

**Enter your config**
Configure in the normal way.

**Describe the bug**
In the log of the terminal, I found that the log was stuck in one place for a long time without moving, until a long time later, when the first prompt that appeared again was Backuper's check and update failure prompt. Therefore, I speculate that this stuck may be related to Backuper's check and update.
Since the area where my server is located has strong network access restrictions, most of the time it is impossible to stably access websites other than the country where the server is located, which causes the startup process to get stuck.

**Describe the way to reproduce the bug**
Can disable the option to check for updated in config.

log is here:
[lastest.log](https://github.com/user-attachments/files/15834754/lastest.log)

**Comment by DVDishka** [comment]
I'm very glad you created your issue right now, as I was just about to release a version to support 1.21)) Today I will add a parameter to the config that allows you to disable the update check for the backuper and release the new version

**Comment by DVDishka** [comment]
Now please download the new version of the plugin and let me know if the problem has been resolved

**Comment by LrbsX** [comment]
> Now please download the new version of the plugin and let me know if the problem has been resolved

Yes, after disabling updates, Backuper no longer causes stuck during the server startup process.
