### ISSUE TITLE
[HELP] - Timezone/BackupTime

### ISSUE THREAD

**Issue by bandlaw12** [DVDishka/Backuper#25]
Not sure if this is intentional or not, but the backupTime doesn't line up with my server time. For example, I have my config to set to:

```
  # (0 - 23). Automatic backups will be made at this time every day. (backupPeriod will be automatically set to 24 hours). -1 to disable backup time fixation
  backupTime: 2
```

but it backs up every night at 10pm  local (I'm in EST in a location that observes DST), meaning I THINK the server is observing GMT, not local time.

Option 1 - add comment to the # to clarify that it is GMT time
Option 2 - add setting for setting timezone (and/or)
Option 3 - setting default to local server time instead of GMT

Thank you for developing this plugin!

**Comment by DVDishka** [comment]
Thank you for your report, I will fix it in near future

**Comment by DVDishka** [comment]
Are you sure that the time on the server is set correctly? I mean exactly the time on the minecraft server itself,. If possible, please send me a log file. Maybe you are using docker or something like that and the time in the container does not match the time on your physical server

**Comment by DVDishka** [comment]
Thank you for your report. Please close the issue when you are sure everything is working
