### ISSUE TITLE
[BUG]An error is reported when the plug-in is running on the purpur server

### ISSUE THREAD

**Issue by enderLuoxh** [DVDishka/Backuper#26]
**Specify your operating system, minecraft server core and minecraft version**
Windows server2022    purpur-1.21-2268
**Enter your config**

**Describe the bug**
![Uploading 0f0ca0bea68fc6ed5089f55be1376b4e.png…]()
![64D0B85BBCECFB618E6E266A25533688](https://github.com/user-attachments/assets/9b944d02-acee-40eb-8846-bd4dc175b355)
![46F9EBB0D3852EBDBF678E47C3C462D1](https://github.com/user-attachments/assets/3cd29a96-da2d-4478-9a8c-e406dba1ca86)

**Describe the way to reproduce the bug**
Just put the plugin into the server side of this version I said and you can reproduce it

**Comment by DVDishka** [comment]
Please attach the configuration file

**Comment by enderLuoxh** [comment]
`# DO NOT CHANGE
configVersion: 8.0
lastBackup: 0
lastChange: 0

backup:
  # (true/false) Automatic backup once in a specified period
  autoBackup: false
  # (Path list) (An example of how to set a list is below) Full directory paths to folders/files that you want to be backed up. Worlds will be backed up automatically, so you do not need to specify world folders there (For example you can specify "plugins", "config")
  # addDirectoryToBackup:
  # - path1
  # - path2
  # - ...
  addDirectoryToBackup: []
  # (Path list) (An example of how to set a list is below) Full directory paths to folders/files that you want to be excluded from backup. If you want to backup everything from the folder1 except some folder1/file1 you can specify folder1 in addDirectoryToBackup and folder1/file1 in excludeDirectoryFromBackup. (The backupsFolder directory will be excluded automatically to prevent the loop)
  # excludeDirectoryFromBackup:
  # - path1
  # - path2
  # - ...
  excludeDirectoryFromBackup: []

  # (MINUTES > 0 or -1) Backup period. To change this value you need to set backupTime to -1 and autoBackup to true
  backupPeriod: 1440
  # (0 - 23). Automatic backups will be made at this time every day. (backupPeriod will be automatically set to 24 hours). -1 to disable backup time fixation
  backupTime: -1

  # (true/false) Sometimes errors may occur while creating a backup. When this option is enabled, such backups will be deleted
  deleteBrokenBackups: true
  # (true/false) The backup will only occur if the world has been changed since the last backup. If the world has not been changed, this backup cycle will be skipped
  skipDuplicateBackup: true
  # (STOP, RESTART, NOTHING) What to do after an automatic backup
  afterBackup: NOTHING

  # (true/false) (True recommended) The backuper will mark all world folders as Read Only to prevent folder changing that may cause the backup crash. True value may cause access denied errors during the backup (you should just ignore that)
  setWorldsReadOnly: false

local:
  # (true/false) Enable local storage to use it via the Backuper
  enabled: true
  # (true/false) With automatic backup, backups will be saved to specified local storage. Works only if 'enabled: true'
  autoBackup: true

  # (Path) Full directory where backups will be stored
  backupsFolder: plugins/Backuper/Backups

  # (>= 0) Max backups in backups folder, 0 to make it unlimited
  maxBackupsNumber: 0
  # (MB >= 0) Max backups folder weight, 0 to make it unlimited
  maxBackupsWeight: 0

  # (true/false) Should backups be packaged in a zip archive
  zipArchive: true
  # (0 - 9) archive compression level. A higher value may reduce file size, but may also increase the time required to archive and decompress
  zipCompressionLevel: 5

ftp:
  # (true/false) Enable FTP storage to use it via the Backuper
  enabled: false
  # (true/false) With automatic backup, backups will be saved to specified FTP server. Works only if 'enabled: true'
  autoBackup: true

  # (Path) FTP server directory where backups will be stored
  backupsFolder: ''
  # (Symbol) Path separator symbol used on FTP SERVER. For example '/' on UNIX systems and '\' on windows
  pathSeparatorSymbol: /

  # (>= 0) Max backups in backups folder, 0 to make it unlimited
  maxBackupsNumber: 0
  # (MB >= 0) Max backups folder weight, 0 to make it unlimited
  maxBackupsWeight: 0

  # (true/false) Should backups be packaged in a zip archive
  zipArchive: true
  # (0 - 9) archive compression level. A higher value may reduce file size, but may also increase the time required to archive and decompress
  zipCompressionLevel: 5

  auth:
    # (Address) FTP server address
    address: ''
    # (Port) FTP server port
    port: 21
    # (Username) FTP server username to use for authentication
    username: ''
    # (Password) FTP server password to use for authentication
    password: ''

sftp:
  # (true/false) Enable SFTP storage to use it via the Backuper
  enabled: false
  # (true/false) With automatic backup, backups will be saved to specified SFTP server. Works only if 'enabled: true'
  autoBackup: true

  # (Path) SFTP server directory where backups will be stored
  backupsFolder: ''
  # (Symbol) Path separator symbol used on SFTP SERVER. For example '/' on UNIX systems and '\' on windows
  pathSeparatorSymbol: /

  # (>= 0) Max backups in backups folder, 0 to make it unlimited
  maxBackupsNumber: 0
  # (MB >= 0) Max backups folder weight, 0 to make it unlimited
  maxBackupsWeight: 0

  auth:
    # (Address) SFTP server address
    address: ''
    # (Port) FTP server port
    port: 22
    # (password/key) SFTP server authentication type
    authType: password
    # (Username) FTP server username to use for authentication
    username: ''
    # (Password) FTP server password to use for authentication
    password: ''
    # (Absolute Path) Local path to key file if 'authType: key'
    keyFilePath: ''
    # (true/false) Do you want to specify local knownHostsFile?
    useKnownHostsFile: false
    # (Path) Path to local knownHostsFile if 'useKnownHostsFile: true'
    knownHostsFilePath: ''

server:
  # (SECONDS < backupPeriod * 60 or -1) A notification about the server restart will be sent to all players on the server {alertTimeBeforeRestart} seconds before the restart. -1 to disable notifications
  alertTimeBeforeRestart: 60
  # (true/false) Notifications will be sent only if the server will be restarted or stopped after the backup
  alertOnlyServerRestart: true

  # (true/false) Check for new versions of the Backuper to stay up to date
  checkUpdates: true

  # (true/false) Better logging (Some statistic and other information for debugging, you probably don't need it)
  betterLogging: false`

**Comment by enderLuoxh** [comment]
# DO NOT CHANGE
configVersion: 8.0
lastBackup: 0
lastChange: 0

backup:
  # (true/false) Automatic backup once in a specified period
  autoBackup: false
  # (Path list) (An example of how to set a list is below) Full directory paths to folders/files that you want to be backed up. Worlds will be backed up automatically, so you do not need to specify world folders there (For example you can specify "plugins", "config")
  # addDirectoryToBackup:
  # - path1
  # - path2
  # - ...
  addDirectoryToBackup: []
  # (Path list) (An example of how to set a list is below) Full directory paths to folders/files that you want to be excluded from backup. If you want to backup everything from the folder1 except some folder1/file1 you can specify folder1 in addDirectoryToBackup and folder1/file1 in excludeDirectoryFromBackup. (The backupsFolder directory will be excluded automatically to prevent the loop)
  # excludeDirectoryFromBackup:
  # - path1
  # - path2
  # - ...
  excludeDirectoryFromBackup: []

  # (MINUTES > 0 or -1) Backup period. To change this value you need to set backupTime to -1 and autoBackup to true
  backupPeriod: 1440
  # (0 - 23). Automatic backups will be made at this time every day. (backupPeriod will be automatically set to 24 hours). -1 to disable backup time fixation
  backupTime: -1

  # (true/false) Sometimes errors may occur while creating a backup. When this option is enabled, such backups will be deleted
  deleteBrokenBackups: true
  # (true/false) The backup will only occur if the world has been changed since the last backup. If the world has not been changed, this backup cycle will be skipped
  skipDuplicateBackup: true
  # (STOP, RESTART, NOTHING) What to do after an automatic backup
  afterBackup: NOTHING

  # (true/false) (True recommended) The backuper will mark all world folders as Read Only to prevent folder changing that may cause the backup crash. True value may cause access denied errors during the backup (you should just ignore that)
  setWorldsReadOnly: false

local:
  # (true/false) Enable local storage to use it via the Backuper
  enabled: true
  # (true/false) With automatic backup, backups will be saved to specified local storage. Works only if 'enabled: true'
  autoBackup: true

  # (Path) Full directory where backups will be stored
  backupsFolder: plugins/Backuper/Backups

  # (>= 0) Max backups in backups folder, 0 to make it unlimited
  maxBackupsNumber: 0
  # (MB >= 0) Max backups folder weight, 0 to make it unlimited
  maxBackupsWeight: 0

  # (true/false) Should backups be packaged in a zip archive
  zipArchive: true
  # (0 - 9) archive compression level. A higher value may reduce file size, but may also increase the time required to archive and decompress
  zipCompressionLevel: 5

ftp:
  # (true/false) Enable FTP storage to use it via the Backuper
  enabled: false
  # (true/false) With automatic backup, backups will be saved to specified FTP server. Works only if 'enabled: true'
  autoBackup: true

  # (Path) FTP server directory where backups will be stored
  backupsFolder: ''
  # (Symbol) Path separator symbol used on FTP SERVER. For example '/' on UNIX systems and '\' on windows
  pathSeparatorSymbol: /

  # (>= 0) Max backups in backups folder, 0 to make it unlimited
  maxBackupsNumber: 0
  # (MB >= 0) Max backups folder weight, 0 to make it unlimited
  maxBackupsWeight: 0

  # (true/false) Should backups be packaged in a zip archive
  zipArchive: true
  # (0 - 9) archive compression level. A higher value may reduce file size, but may also increase the time required to archive and decompress
  zipCompressionLevel: 5

  auth:
    # (Address) FTP server address
    address: ''
    # (Port) FTP server port
    port: 21
    # (Username) FTP server username to use for authentication
    username: ''
    # (Password) FTP server password to use for authentication
    password: ''

sftp:
  # (true/false) Enable SFTP storage to use it via the Backuper
  enabled: false
  # (true/false) With automatic backup, backups will be saved to specified SFTP server. Works only if 'enabled: true'
  autoBackup: true

  # (Path) SFTP server directory where backups will be stored
  backupsFolder: ''
  # (Symbol) Path separator symbol used on SFTP SERVER. For example '/' on UNIX systems and '\' on windows
  pathSeparatorSymbol: /

  # (>= 0) Max backups in backups folder, 0 to make it unlimited
  maxBackupsNumber: 0
  # (MB >= 0) Max backups folder weight, 0 to make it unlimited
  maxBackupsWeight: 0

  auth:
    # (Address) SFTP server address
    address: ''
    # (Port) FTP server port
    port: 22
    # (password/key) SFTP server authentication type
    authType: password
    # (Username) FTP server username to use for authentication
    username: ''
    # (Password) FTP server password to use for authentication
    password: ''
    # (Absolute Path) Local path to key file if 'authType: key'
    keyFilePath: ''
    # (true/false) Do you want to specify local knownHostsFile?
    useKnownHostsFile: false
    # (Path) Path to local knownHostsFile if 'useKnownHostsFile: true'
    knownHostsFilePath: ''

server:
  # (SECONDS < backupPeriod * 60 or -1) A notification about the server restart will be sent to all players on the server {alertTimeBeforeRestart} seconds before the restart. -1 to disable notifications
  alertTimeBeforeRestart: 60
  # (true/false) Notifications will be sent only if the server will be restarted or stopped after the backup
  alertOnlyServerRestart: true

  # (true/false) Check for new versions of the Backuper to stay up to date
  checkUpdates: true

  # (true/false) Better logging (Some statistic and other information for debugging, you probably don't need it)
  betterLogging: false

**Comment by enderLuoxh** [comment]
[config.txt](https://github.com/user-attachments/files/16312349/config.txt)

**Comment by DVDishka** [comment]
Is there a plugins/Backuper/Backups folder on your server?

**Comment by enderLuoxh** [comment]
yes

**Comment by enderLuoxh** [comment]
This is what started after I migrated the plugin from the paper server to the purpur server

**Comment by DVDishka** [comment]
Is the backup process working well? Does the /backuper list local command work?

**Comment by enderLuoxh** [comment]
I've tried, but this command is invalid, it will prompt a bug, and then when I execute it again, it will prompt that another process is blocking the execution of this task

**Comment by DVDishka** [comment]
What happens when using /backuper backup local? Is a backup created?

**Comment by enderLuoxh** [comment]
Only an error message appears, and no backup file is generated

**Comment by DVDishka** [comment]
Please send me these errors

**Comment by enderLuoxh** [comment]
I'm serving because of the plug-in error.,I've uninstalled this plug-in.,I'll reproduce it when I have time later.,But it's the version of purpur I sent plus the bug in the version of the current plug-in.

**Comment by enderLuoxh** [comment]
I tried the new purpur server today, and this error seems to have disappeared, I speculate that it may be an incompatible bug that appeared in the build stage of the server, thanks
