### ISSUE TITLE
Does Paper's auto-save pause during backup? 

### ISSUE THREAD

**Issue by Julyxunle** [DVDishka/Backuper#3]
I would like to inquire whether the original server-side saving of Paper will be paused during the backup process performed by the plugin. I am concerned that if the server-side saving continues while the backup is happening, it may result in incorrect archiving of files from different timeframes.

**Comment by DVDishka** [comment]
Paper auto-save stops during backup. I should know, is this just a question out of interest or are you having any problems using the plugin?

**Comment by DVDishka** [comment]
Paper auto-save stops during backup. I should know, is this just a question out of interest or are you having any problems using the plugin?

**Comment by Julyxunle** [comment]
> Paper auto-save stops during backup. I should know, is this just a question out of interest or are you having any problems using the plugin?

This is just a a question out of interest because I have encountered similar issues with backup software before. I had to manually pause the saving process before initiating the backup. That's why I'm concerned about this aspect. Thank you for your response.

**Comment by DVDishka** [comment]
Thanks for a question
