### ISSUE TITLE
Error in Modrinth description

### ISSUE THREAD

**Issue by vtomes** [DVDishka/Backuper#35]
The explanation of the copyToLocal command seems to be a duplicate of the copyToSftp command explanation in the description on Modrinth.

![Screenshot_17](https://github.com/user-attachments/assets/dfef2127-1d92-4714-bd6b-0b7d945e2a44)

Shouldn't it say "Command to copy the specified backup from SFTP storage to local storage" instead?

**Comment by DVDishka** [comment]
Thank you for your report, I will fix it right now
