### ISSUE TITLE
[HELP] Default value for setWorldsReadOnly = false?

### ISSUE THREAD

**Issue by tibequadorian** [DVDishka/Backuper#38]
Recommended value is true but default value is false? https://github.com/DVDishka/Backuper/commit/8d8362c1efadab61891b2f26f28ff2457480421a

**Comment by DVDishka** [comment]
It isn't a bug. setWorldsReadOnly may produce some server warnings so I don't want to enable this feature by default but the Backuper works more stable with it enabled

**Comment by tibequadorian** [comment]
Alright, just wanted to ask why it is like that :)
