### ISSUE TITLE
help me

### ISSUE THREAD

**Issue by Nishii3333** [DVDishka/Backuper#39]
How do I write the path when backing up to a Windows FTP server?
I tried D:\FTP\svl\Backups and FTP\svl\Backups, but it failed.

[02:08:21 WARN]: [Backuper] Something went wrong while running FtpAddLocalDirToZIP task
[02:08:21 WARN]: [Backuper] FtpAddLocalDirsToZipTask: null
[java.base/java.util.zip.DeflaterOutputStream.<init>(DeflaterOutputStream.java:83), java.base/java.util.zip.DeflaterOutputStream.<init>(DeflaterOutputStream.java:141), java.base/java.util.zip.ZipOutputStream.<init>(ZipOutputStream.java:133), java.base/java.util.zip.ZipOutputStream.<init>(ZipOutputStream.java:119), Backuper-3.1.2.jar//ru.dvdishka.backuper.backend.tasks.ftp.FtpAddLocalDirsToZipTask.run(FtpAddLocalDirsToZipTask.java:67), Backuper-3.1.2.jar//ru.dvdishka.backuper.backend.tasks.common.BackupTask.run(BackupTask.java:137), Backuper-3.1.2.jar//ru.dvdishka.backuper.handlers.commands.backup.BackupCommand.lambda$execute$1(BackupCommand.java:139), Backuper-3.1.2.jar//ru.dvdishka.backuper.backend.common.Scheduler.lambda$runAsync$3(Scheduler.java:46), io.papermc.paper.threadedregions.scheduler.FoliaAsyncScheduler$AsyncScheduledTask.run(FoliaAsyncScheduler.java:217), java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144), java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642), java.base/java.lang.Thread.run(Thread.java:1583)]

**Comment by DVDishka** [comment]
Try to use /, not \ and let me know if that doesn't work

**Comment by Nishii3333** [comment]
I was able to successfully back up!
Thx you!
