### ISSUE TITLE
[BUG] errors when item is picked up

### ISSUE THREAD

**Issue by ehl0el** [DVDishka/Backuper#7]
**Specify your operating system, minecraft server core and minecraft version**

Paper 1.20.4

**Enter your config**

![](https://puu.sh/K1iUV/92b30dd9e4.png)

![](https://puu.sh/K1iVp/4aac97ec4e.png)

**Describe the bug**

console is spammed with errors.

**Comment by DVDishka** [comment]
Can you send me your backuper confg please? (plugins/Backuper/config.yml)

**Comment by ehl0el** [comment]
https://pastebin.com/zJKVBPqs

i haven't changed anything

**Comment by DVDishka** [comment]
Ok, thanks

**Comment by DVDishka** [comment]
Does this happen every time you pick up an item or only sometimes?

**Comment by DVDishka** [comment]
Is the problem fixed by restarting the server?

**Comment by ehl0el** [comment]
seems like every time an item is picked up. there are currently a couple people on the server. I will test restarting in a couple minutes.

**Comment by ehl0el** [comment]
no more errors after restart. anything in specific i should test?

**Comment by DVDishka** [comment]
Last time the errors started appearing after the server start or after some specific moment? Was it the first time the plugin was enabled? Try making a backup and check if there are some errors

**Comment by ehl0el** [comment]
first time installing the plugin. /backup works now with no issues. on server start

**Comment by DVDishka** [comment]
So there are no issues when you trying to pick up an item after backup?

**Comment by ehl0el** [comment]
not anymore. for now at least. also thank you for the fast response!

**Comment by ehl0el** [comment]
is it possible to have a server announcement before/during/after backup?

**Comment by DVDishka** [comment]
Please, open a new Feature request issue

**Comment by DVDishka** [comment]
I found what the problem was, thanks for the feedback, you can always open a new issue if you have any problem or idea
