### ISSUE TITLE
[BUG] Skip duplicate backup Can't Work!

### ISSUE THREAD

**Issue by xiao-k233** [DVDishka/Backuper#8]
**Specify your operating system, minecraft server core and minecraft version**
Debian 12,zing jdk 17,paper1.19.4
**Enter your config**
```
# DO NOT CHANGE
configVersion: 5.0
lastBackup: 1708512755
lastChange: 0
# Automatic backup once in a specified period
autoBackup: true
# Full directory where backups will be stored
backupsFolder: /Main/backup
# Backup time (0 - 23). Backups will be made at this time every day. (backupPeriod will be automatically set to 24 hours). -1 to disable backup time fixation
backupTime: -1
# Backup period in MINUTES. To change this value you need to set backupTime to -1
backupPeriod: 120
# What to do after backup, (STOP, RESTART, NOTHING)
afterBackup: NOTHING
# The backup will only occur if the world has been changed since the last backup. If the world has not been changed, this backup cycle will be skipped
skipDuplicateBackup: true
# Max backups in backups folder, 0 to make it unlimited
maxBackupsNumber: 10
# Max backups folder weight in MB, 0 to make it unlimited
maxBackupsWeight: 0
# Should backups be packaged in a zip archive
zipArchive: true
# Better logging
betterLogging: true
```
**Describe the bug**
`[11:31:07 ERROR]: [Backuper] Failed to register events for class ru.dvdishka.backuper.handlers.WorldChangeCatcher because io/papermc/paper/event/player/PlayerPickItemEvent does not exist.`
And Skip duplicate backup can't work,plugin will never backup though player changed worlds!

**Comment by DVDishka** [comment]
Hmm, apparently this issue is related to compatibility with versions below 1.20. Thanks for the feedback, I'll fix it today, sorry for the inconvenience

**Comment by DVDishka** [comment]
Does the backuper works correctly with disabled skipDuplicateBackup option?

**Comment by xiao-k233** [comment]
> Does the backuper works correctly with disabled skipDuplicateBackup option?

yes
